{
    branches:
        [{ name: "master" }, { name: "rc", channel: "rc", prerelease: true }],
    plugins:
        [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/changelog",
            [
                "@semantic-release/git",
                {
                    "assets": ["api/*.py"],
                    "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
                },
            ],
            "@semantic-release/github",
        ],
}
