name: Auto-Update PRs

on:
    push:
        branches: [master]

permissions:
    contents: read

jobs:
    autoupdate:
        name: Auto-update PRs
        runs-on: ubuntu-latest
        steps:
            - name: Auto-update all PRs
              uses: chinthakagodawita/autoupdate@0707656cd062a3b0cf8fa9b2cda1d1404d74437e # v1.7.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PR_FILTER: "all"
                  PR_READY_STATE: "ready_for_review"
                  MERGE_CONFLICT_ACTION: "fail"
