# Static Application Security Testing
name: Bandit

on:
    workflow_call:
    push:
        branches: [master]
        paths:
            - ".github/workflows/bandit.yml"
            - "**/*.py"
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    sast-scan:
        if: |
            github.actor != 'dependabot[bot]' &&
            github.actor != 'github-actions[bot]' &&
            github.actor != 'protected-auto-commits[bot]'
        name: Bandit Scan
        concurrency: sast-scan
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner
              uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
              with:
                  egress-policy: audit
                  disable-telemetry: true
                  disable-sudo: true

            - name: Checkout Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install Bandit
              run: pip install bandit==1.8.6

            - name: Run Bandit Scan
              run: bandit -r . -f json -o bandit-report.json

            - name: Upload Bandit Scan Results
              if: always()
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
              with:
                  name: bandit-scan-results
                  path: bandit-report.json
