name: Codecov

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/coverage.yml"
            - "tests/*.py"
            - "sonar-project.properties"
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    code-coverage:
        if: |
            github.actor != 'dependabot[bot]' &&
            github.actor != 'github-actions[bot]' &&
            github.actor != 'protected-auto-commits[bot]'
        permissions:
            contents: read
            pull-requests: write
        name: Codecov
        runs-on: ubuntu-latest
        concurrency: code-coverage
        steps:
            - name: Harden the runner
              uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
              with:
                  egress-policy: audit
                  disable-telemetry: true

            - name: Checkout Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install Dependencies
              run: |
                  pip install -r requirements.txt
                  playwright install --with-deps chromium

            - name: Run tests with coverage
              run: |
                  pytest --cov=api --cov-report=xml --cov-report=term-missing
              env:
                  INPUT_STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
                  INPUT_STEAM_ID: ${{ vars.STEAM_ID }}
                  INPUT_STEAM_CUSTOM_ID: ${{ vars.STEAM_CUSTOM_ID }}
                  INPUT_WORKSHOP_STATS: True
                  INPUT_LOG_SCALE: True
                  GITHUB_REPOSITORY: ${{ github.repository }}

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: true

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
