name: Codecov

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/coverage.yml"
            - "tests/*.py"
            - "sonar-project.properties"
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    code-coverage:
        if: |
            github.actor != 'dependabot[bot]' &&
            github.actor != 'github-actions[bot]' &&
            github.actor != 'protected-auto-commits[bot]'
        permissions:
            contents: read
            pull-requests: write
        name: Codecov
        runs-on: ubuntu-latest
        concurrency: code-coverage
        steps:
            - name: Harden the runner
              uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
              with:
                  egress-policy: audit
                  disable-telemetry: true

            - name: Checkout Code
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install Dependencies
              run: |
                  pip install -r requirements.txt
                  playwright install --with-deps chromium

            - name: Run tests with coverage
              run: |
                  pytest --cov=api --cov-report=xml --cov-report=term-missing
              env:
                  INPUT_STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
                  INPUT_STEAM_ID: ${{ vars.STEAM_ID }}
                  INPUT_STEAM_CUSTOM_ID: ${{ vars.STEAM_CUSTOM_ID }}
                  INPUT_WORKSHOP_STATS: True
                  INPUT_LOG_SCALE: True
                  GITHUB_REPOSITORY: ${{ github.repository }}

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: true

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
