name: Docker CICD

on:
    push:
        branches:
        - master
        paths:
        - '**/*.py'
        - 'Dockerfile'
    pull_request:
        branches:
        - master
        paths:
        - '**/*.py'
        - 'Dockerfile'

jobs:
    changed_files:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                fetch-depth: 1

          - name: Detect Changes
            id: changed-files
            uses: tj-actions/changed-files@v44

          - name: List all Changes
            env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
            run: |
                for file in ${ALL_CHANGED_FILES}; do
                    echo "$file was changed"
                done

    build-and-publish:
        runs-on: ubuntu-latest
        needs: changed_files
        if: needs.changed_files.outputs.changed_files == 'true'
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                fetch-depth: 1

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

          - name: Extract Docker Metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ secrets.DOCKER_USERNAME }}/steam-stats

          - name: Build & Push Docker Image
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    update-changelog:
        runs-on: ubuntu-latest
        needs: build-and-publish
        if: success()
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
                fetch-depth: 1

          - name: Extract release date from git tag
            id: release_date
            run: |
                echo "date=$(git log -1 --date=short --format=%ad '${{ github.event.release.tag_name }}')" >> $GITHUB_OUTPUT;

          - name: Update Changelog
            uses: stefanzweifel/changelog-updater-action@v1
            with:
                release-date: ${{ steps.release_date.outputs.date }}
                release-notes: ${{ github.event.release.body }}
                latest-version: ${{ github.event.release.tag_name }}

          - name: Commit Updated CHANGELOG
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                branch: master
                commit_message: Update CHANGELOG
                file_pattern: CHANGELOG.md
