name: CICD

on:
    push:
        branches:
        - master
        paths:
        - '**/*.py'
        - 'Dockerfile'
    pull_request:
        branches:
        - master
        paths:
        - '**/*.py'
        - 'Dockerfile'

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            changes_detected: ${{ steps.detect-changes.outputs.changes_detected }}
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Detect Changes
            id: detect-changes
            uses: tj-actions/changed-files@v44
            with:
                files: |
                    **/*.py
                    Dockerfile

    build-and-publish:
        runs-on: ubuntu-latest
        needs: detect-changes
        if: needs.detect-changes.outputs.changes_detected == 'true'
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

          - name: Extract Docker Metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ secrets.DOCKER_USERNAME }}/steam-stats

          - name: Build & Push Docker Image
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    update-changelog:
        runs-on: ubuntu-latest
        needs: build-and-publish
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Extract release date from git tag
            id: release_date
            run: |
                echo "date=$(git log -1 --date=short --format=%ad '${{ github.event.release.tag_name }}')" >> $GITHUB_OUTPUT;

          - name: Update Changelog
            uses: stefanzweifel/changelog-updater-action@v1
            with:
                release-date: ${{ steps.release_date.outputs.date }}
                release-notes: ${{ github.event.release.body }}
                latest-version: ${{ github.event.release.tag_name }}

          - name: Commit Updated CHANGELOG
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                branch: master
                commit_message: Update CHANGELOG
                file_pattern: CHANGELOG.md
