name: Deploy MkDocs

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/docs.yml"
            - "docs/**"
            - "mkdocs.yml"

permissions:
    contents: read

jobs:
    build:
        name: Build Docs
        concurrency:
            group: pages-deploy
            cancel-in-progress: true
        if: |
            github.actor != 'dependabot[bot]' &&
            github.actor != 'github-actions[bot]' &&
            github.actor != 'protected-auto-commits[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner
              uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
              with:
                  egress-policy: audit
                  disable-telemetry: true
                  disable-sudo: true

            - name: GitHub App Token
              uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
              id: app-token
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Checkout Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0
                  token: ${{ steps.app-token.outputs.token }}

            - name: Setup Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install Dependencies
              run: pip install ".[docs]"

            - name: Build Documentation
              run: mkdocs build --clean --strict
              env:
                  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

            - name: Setup Pages
              uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
              with:
                  path: ./site

    deploy:
        name: Deploy Docs
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Harden the runner
              uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
              with:
                  egress-policy: audit
                  disable-telemetry: true
                  disable-sudo: true

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
