name: Lint and Quality Check

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
    lint:
        name: Lint Code Base
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

          - name: Set PYTHONPATH
            run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

          - name: Run Pylint
            run: |
                pip install pylint
                pylint api/main.py api/steam_stats.py api/steam_workshop.py

    quality-check:
        name: Quality Check
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

          - name: Run Pylint
            run: |
                pip install pylint
                pylint api/main.py api/steam_stats.py api/steam_workshop.py

          - name: Run Flake8
            run: |
                pip install flake8
                flake8 api/main.py api/steam_stats.py api/steam_workshop.py
