name: Pylint

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - '.github/workflows/pylint.yml'
            - '**/*.py'
    pull_request:
        branches:
        - master

jobs:
    build:
        name: Quality Check
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'
                cache: "pip"

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

          - name: Pylint Badge
            uses: Silleellie/pylint-github-action@v2
            with:
                lint-path: api
                python-version: 3.x
                requirements-path: requirements.txt
                readme-path: README.md
                badge-text: PyLint
                color-bad-score: red
                color-ok-score: orange
                color-good-score: yellow
                color-perfect-score: brightgreen
